version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jsonplaceholder-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jsonplaceholder
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - jsonplaceholder-network

  db:
    image: postgres:16-alpine
    container_name: jsonplaceholder-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jsonplaceholder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jsonplaceholder-network

volumes:
  postgres-data:
    name: jsonplaceholder-postgres-data

networks:
  jsonplaceholder-network:
    name: jsonplaceholder-network 