jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 900000 # 15 minutes in milliseconds
  refresh-token:
    expiration: 604800000 # 7 days in milliseconds

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jsonplaceholder
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml 